# Generated by Django 2.2 on 2020-06-08 09:13

from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HabitTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2200)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('recurrences', recurrence.fields.RecurrenceField(null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HabitPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.HabitTrack')),
            ],
            options={
                'ordering': ['-publish_date', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HabitEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.HabitPost')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.HabitTrack')),
            ],
        ),
    ]
