# Generated by Django 2.2 on 2020-06-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitevent',
            name='date',
        ),
        migrations.AddField(
            model_name='habitevent',
            name='date_expected',
            field=models.DateField(null=True),
        ),
    ]
