# Generated by Django 2.1.5 on 2020-05-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitpost',
            name='slug',
            field=models.SlugField(default='first', unique=True),
            preserve_default=False,
        ),
    ]
