# Generated by Django 2.1.5 on 2020-05-31 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0002_habitpost_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='habitpost',
            name='id',
        ),
        migrations.RemoveField(
            model_name='habitpost',
            name='user',
        ),
        migrations.CreateModel(
            name='HabitEvent',
            fields=[
                ('habitmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='habits.HabitModel')),
            ],
            bases=('habits.habitmodel',),
        ),
        migrations.CreateModel(
            name='HabitTrack',
            fields=[
                ('habitmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='habits.HabitModel')),
                ('track_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2200)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
            bases=('habits.habitmodel',),
        ),
        migrations.AddField(
            model_name='habitmodel',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='habitpost',
            name='habitmodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='habits.HabitModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitpost',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.HabitTrack'),
        ),
    ]
