# Generated by Django 2.2 on 2020-06-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_auto_20200610_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitpost',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
