# Generated by Django 2.2 on 2020-06-15 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_auto_20200615_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitpost',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='habitpost',
            name='publish_date',
        ),
    ]
