# Generated by Django 2.2 on 2020-06-19 20:25

from django.db import migrations, models
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_auto_20200615_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='JustRecurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurrences', recurrence.fields.RecurrenceField(null=True)),
            ],
        ),
    ]
