# Generated by Django 2.2 on 2020-07-12 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_justrecurrence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habittrack',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterField(
            model_name='habitmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='habittrack',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
