# Generated by Django 2.2 on 2020-07-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_auto_20200712_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='habittrack',
            name='slug',
            field=models.SlugField(default='trackslug'),
        ),
    ]
