# Generated by Django 2.2 on 2020-07-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_habittrack_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habittrack',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
