# Generated by Django 2.2 on 2020-08-18 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0009_auto_20200818_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='habitmodel_ptr',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='habitmodel_ptr',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='post',
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
