# Generated by Django 2.2 on 2020-08-18 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0010_auto_20200818_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('habitmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='habits.HabitModel')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.HabitPost')),
            ],
            bases=('habits.habitmodel',),
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('habitmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='habits.HabitModel')),
                ('comment', models.TextField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.PostComment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.HabitPost')),
            ],
            bases=('habits.habitmodel',),
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('habitmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='habits.HabitModel')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.PostComment')),
            ],
            bases=('habits.habitmodel',),
        ),
    ]
