# Generated by Django 2.2 on 2020-10-19 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0013_auto_20200921_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitevent',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_event', to='habits.HabitPost'),
        ),
    ]
