# Generated by Django 2.2 on 2020-10-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0014_auto_20201019_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitpost',
            name='image',
            field=models.ImageField(null=True, upload_to='image/image_2'),
        ),
    ]
