# Generated by Django 2.2 on 2020-10-28 21:47

from django.db import migrations, models
import habits.models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0015_auto_20201028_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitpost',
            name='image',
            field=models.ImageField(null=True, upload_to=habits.models.photo_path),
        ),
        migrations.AlterField(
            model_name='habittrack',
            name='cover_image',
            field=models.ImageField(null=True, upload_to=habits.models.photo_path),
        ),
    ]
