# Generated by Django 2.2 on 2020-10-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0016_auto_20201028_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habittrack',
            options={'ordering': ['-start_date', '-creation_date']},
        ),
        migrations.AddField(
            model_name='habittrack',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
