# Generated by Django 2.2 on 2020-11-12 19:32

from django.db import migrations, models
import recurrence.fields
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0017_auto_20201028_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='habittrack',
            name='timezone1',
            field=timezone_field.fields.TimeZoneField(default='America/Los_Angeles'),
        ),
        migrations.AlterField(
            model_name='habittrack',
            name='recurrences',
            field=recurrence.fields.RecurrenceField(),
        ),
        migrations.AlterField(
            model_name='habittrack',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
