# Generated by Django 2.2 on 2020-11-12 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0018_auto_20201112_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habittrack',
            old_name='timezone1',
            new_name='timezone',
        ),
    ]
