# Generated by Django 2.2 on 2021-01-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0019_auto_20201112_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitpost',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
