# Generated by Django 2.2 on 2021-01-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0020_auto_20210124_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='habittrack',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
