# Generated by Django 2.2 on 2020-09-21 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200921_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['account_creation_date']},
        ),
    ]
