# Generated by Django 2.2 on 2020-10-28 22:15

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20201028_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=profiles.models.photo_path),
        ),
    ]
